// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJnTlIBTmDFDnVJuJw85IduKYyVcxXOvs',
    appId: '1:308893447553:web:c0493d1ad41fa440396480',
    messagingSenderId: '308893447553',
    projectId: 'for-you-daily',
    authDomain: 'for-you-daily.firebaseapp.com',
    storageBucket: 'for-you-daily.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxmFZv_zdgyhVOtkEkYA8Ld2B4ba3hzx0',
    appId: '1:308893447553:android:2351755e164daa43396480',
    messagingSenderId: '308893447553',
    projectId: 'for-you-daily',
    storageBucket: 'for-you-daily.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRshodYzwba4wg78EdtpvOryP6tOv3ovs',
    appId: '1:308893447553:ios:17321e8211fb60d1396480',
    messagingSenderId: '308893447553',
    projectId: 'for-you-daily',
    storageBucket: 'for-you-daily.firebasestorage.app',
    iosBundleId: 'com.example.forYouDaily',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRshodYzwba4wg78EdtpvOryP6tOv3ovs',
    appId: '1:308893447553:ios:17321e8211fb60d1396480',
    messagingSenderId: '308893447553',
    projectId: 'for-you-daily',
    storageBucket: 'for-you-daily.firebasestorage.app',
    iosBundleId: 'com.example.forYouDaily',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJnTlIBTmDFDnVJuJw85IduKYyVcxXOvs',
    appId: '1:308893447553:web:f316dfd6a6f8cc0c396480',
    messagingSenderId: '308893447553',
    projectId: 'for-you-daily',
    authDomain: 'for-you-daily.firebaseapp.com',
    storageBucket: 'for-you-daily.firebasestorage.app',
  );
}
